import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { GpaSystem } from "../../data/gpaSystems";
import type { Semester } from "./calc";
import { coursePoints, courseUnweighted4, semesterTotals } from "./calc";

// Illuminate brand navy / royal blue, as sRGB — jsPDF has no access to the
// page's CSS custom properties, so these are copied from app.css's
// light-mode --color-chalkboard / --color-pen.
const NAVY: [number, number, number] = [21, 24, 46];
const BLUE: [number, number, number] = [43, 68, 171];
const GRAY: [number, number, number] = [110, 115, 130];

export function downloadTranscriptPdf(opts: {
  studentName: string;
  studentEmail: string;
  system: GpaSystem;
  semesters: Semester[];
  priorGpa: number | null;
  priorCredits: number | null;
  cumulativeWeighted: number;
  cumulativeUnweighted: number;
  totalCredits: number;
}) {
  const { studentName, system, semesters, cumulativeWeighted, cumulativeUnweighted, totalCredits } = opts;
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...NAVY);
  doc.text("Illuminate", margin, 56);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("Free K–12 academic guidance, student-run · illuminate.org", margin, 72);

  doc.setDrawColor(...BLUE);
  doc.setLineWidth(1.2);
  doc.line(margin, 84, pageWidth - margin, 84);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text("GPA & Course Transcript", margin, 108);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  const generated = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`${studentName}  ·  Generated ${generated}`, margin, 124);
  doc.text(`Scale: ${system.label} (${system.maxScale} max)`, margin, 138);

  let cursorY = 156;

  for (const semester of semesters) {
    const totals = semesterTotals(system, semester.courses);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text(semester.label, margin, cursorY + 14);

    autoTable(doc, {
      startY: cursorY + 22,
      margin: { left: margin, right: margin },
      head: [["Course", "Level", "Grade", "Credits", "Points"]],
      body: semester.courses.map((c) => {
        const type = system.courseTypes.find((t) => t.id === c.courseTypeId);
        const grade = system.scaleType === "raw100" ? String(c.rawScore ?? "") : c.grade || "—";
        return [
          c.name || "Untitled course",
          type?.label ?? "—",
          grade,
          String(c.credits),
          coursePoints(system, c).toFixed(2),
        ];
      }),
      foot: [
        [
          { content: "Semester GPA", colSpan: 4, styles: { halign: "right", fontStyle: "bold" } },
          { content: totals.weighted.toFixed(2), styles: { fontStyle: "bold" } },
        ],
      ],
      styles: { fontSize: 9, cellPadding: 5, textColor: [20, 20, 30] },
      headStyles: { fillColor: BLUE, textColor: 255 },
      footStyles: { fillColor: [240, 242, 248], textColor: [20, 20, 30] },
      theme: "grid",
    });

    // @ts-expect-error jspdf-autotable augments the doc instance at runtime
    cursorY = doc.lastAutoTable.finalY + 26;

    if (cursorY > doc.internal.pageSize.getHeight() - 120) {
      doc.addPage();
      cursorY = 48;
    }
  }

  if (cursorY > doc.internal.pageSize.getHeight() - 140) {
    doc.addPage();
    cursorY = 48;
  }

  doc.setDrawColor(...BLUE);
  doc.setFillColor(246, 247, 251);
  doc.roundedRect(margin, cursorY, pageWidth - margin * 2, 88, 6, 6, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text("CUMULATIVE (INCLUDING PRIOR CREDITS)", margin + 16, cursorY + 22);

  doc.setFontSize(22);
  doc.setTextColor(...NAVY);
  doc.text(cumulativeWeighted.toFixed(2), margin + 16, cursorY + 52);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Weighted · ${system.maxScale} scale`, margin + 16, cursorY + 68);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...BLUE);
  doc.text(cumulativeUnweighted.toFixed(2), margin + 220, cursorY + 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("Unweighted · 4.0 scale", margin + 220, cursorY + 68);

  doc.setFontSize(9);
  doc.text(`${totalCredits} total credits`, pageWidth - margin - 16, cursorY + 52, { align: "right" });

  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY);
  doc.text(
    "Unofficial. Generated by an Illuminate student — not affiliated with or issued by your school district.",
    margin,
    doc.internal.pageSize.getHeight() - 24,
  );

  doc.save("illuminate-transcript.pdf");
}

/** Re-export so callers only need one import for the numbers behind the PDF. */
export { coursePoints, courseUnweighted4 };
